# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-15 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeltag',
            name='tag',
        ),
        migrations.AddField(
            model_name='modeldiscuss',
            name='tag',
            field=models.ManyToManyField(to='App.ModelTag'),
        ),
        migrations.AlterField(
            model_name='modeldiscuss',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
