# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-15 17:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20161015_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldiscuss',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 15, 17, 54, 1, 43977, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
