# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-15 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_modeldiscuss_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeluser',
            name='role',
            field=models.CharField(choices=[('user', 'USER'), ('doctor', 'DOCTOR'), ('expert', 'EXPERT')], default='user', max_length=10),
        ),
    ]
