# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20161016_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldiscuss',
            name='body',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='modelquestion',
            name='question',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
