# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-16 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20161016_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldiscuss',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='modelquestion',
            name='question',
            field=models.TextField(),
        ),
    ]
